package models;

public enum BuildingType {
    CASTLE_BUILDINGS,
    FARM_BUILDINGS,
    FOOD_PROCESSING_BUILDINGS,
    INDUSTRY,
    KEEPS_AND_STRONGHOLDS,
    TOWERS_AND_GATEHOUSES,
    TOWN_BUILDINGS,
    WEAPON_BUILDINGS
}
