package models;

public enum BuildingType {
  CASTLE_BUILDINGS,
  FARM_BUILDINGS,
  FOOD_PROCESSING_BUILDINGS,
  INDUSTRY,
  KEEPS_AND_STRONGHOLDS,
  TOWERS_AND_GATEHOURSES,
  TOWN_BUILDINGS,
  WEAPON_BUILDINGS
}